name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync

    - name: Lint with ruff
      run: uv run ruff check .

    - name: Format with black
      run: uv run black . --check

    - name: Check imports with isort
      run: uv run isort . --check-only --diff

    - name: Type check with mypy
      run: uv run mypy .

    - name: Test with pytest
      run: uv run pytest -v --log-cli-level=INFO
